# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendgroup',
            options={'verbose_name': 'friends list', 'verbose_name_plural': 'friends lists'},
        ),
    ]
