# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendgroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='friendgroup',
            name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='userfriendgroup',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='userfriendgroup',
            name='friend_group',
        ),
        migrations.RemoveField(
            model_name='userfriendgroup',
            name='member',
        ),
        migrations.AlterModelOptions(
            name='friend',
            options={'verbose_name': 'friends', 'verbose_name_plural': 'friends'},
        ),
        migrations.DeleteModel(
            name='FriendGroup',
        ),
        migrations.DeleteModel(
            name='UserFriendGroup',
        ),
    ]
